### ISSUE TITLE
grafana-map-panel not available 

### ISSUE THREAD

**Issue by matt-FFFFFF** [matt-FFFFFF/hassio-addon-repository#5]
This grafana plugin is not available on the "charging stats" page.

This is caused by the plugin being in a third part repo and the HA community addon not being able to add it.

Will submit a PR to the owner of the Grafana addon to add the capability of running customer grafana-cli commands.

**Comment by matt-FFFFFF** [comment]
hassio-addons/addon-grafana#79

**Comment by msvinth** [comment]
> hassio-addons/addon-grafana#79

Sinde frenck do not want to add this generic solution, maybe a less generic solution where it somehow is possible to specify the pluginUrl for a plug-in would be acceptable. Maybe an optional `from <pluginUrl>` added after plug-in name.
E.g.
```
- grafana-map-panel from https://github.com/panodata/grafana-map-panel/releases/download/0.15.0/grafana-map-panel-0.15.0.zip

**Comment by msvinth** [comment]
Or maybe a new plugins property in the config:
```
plugins_ext:
  - name: grafana-map-panel
    url: https://github.com/panodata/grafana-map-panel/releases/download/0.15.0/grafana-map-panel-0.15.0.zip
```

**Comment by ohadlevy** [comment]
since the solution was not accepted upstream, and since I upgraded grafana without realizing v8 is not supported, I ended up creating a new grafana addon, that also include the map-panel plugin and is fixed to v7, you can add it as custom repository from https://github.com/ohadlevy/ha-addons

HTH

**Comment by ohadlevy** [comment]
note that latest version (https://github.com/adriankumpf/teslamate/releases/tag/v1.26.0) has grafana 8 support.

**Comment by matt-FFFFFF** [comment]
🥳

**Comment by matt-FFFFFF** [comment]
see matt-FFFFFF/hassio-addon-teslamate#56

1.26.0 incoming

**Comment by logik3** [comment]
Sorry to bring up an old topic. Did you manage to find out how to install the panodata-map-panel plugin with grafana 8 from HA community addon?

**Comment by llluis** [comment]
> Sorry to bring up an old topic. Did you manage to find out how to install the panodata-map-panel plugin with grafana 8 from HA community addon?

See https://github.com/matt-FFFFFF/hassio-addon-teslamate/issues/74

**Comment by llluis** [comment]
Hello folks. Just to refresh this. My PR was merged into the official Grafana add-on a while ago. So, it's possible to add the missing plugin. **This issue can be closed.**

Here's my current Grafana add-on config:

```
plugins:
  - natel-discrete-panel
  - natel-plotly-panel
  - pr0ps-trackmap-panel
  - grafana-piechart-panel
custom_plugins:
  - name: panodata-map-panel
    url: https://github.com/panodata/panodata-map-panel/releases/download/0.16.0/panodata-map-panel-0.16.0.zip
    unsigned: true
```
